name: Build Wheels
on:
  push:
  workflow_dispatch:

jobs:
  build_wheels:
    name: Build wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu-latest, windows-latest ]

    steps:
    - name: Checkout
      uses: actions/checkout@v6

    - name: Download libbluray
      uses: dawidd6/action-download-artifact@v21
      with:
        github_token: ${{secrets.GITHUB_TOKEN}}
        workflow: build.yml
        name: libbluray
        path: ${{ github.workspace }}/libbluray
        repo: Windows-Media-Tools/libbluray
      if: matrix.os == 'windows-latest'

    - name: Download libaacs
      uses: dawidd6/action-download-artifact@v21
      with:
        github_token: ${{secrets.GITHUB_TOKEN}}
        workflow: build.yml
        name: libaacs
        path: ${{ github.workspace }}/libaacs
        repo: Windows-Media-Tools/libaacs
      if: matrix.os == 'windows-latest'

    - name: Set up Python
      uses: actions/setup-python@v6

    - name: Install cibuildwheel
      run: python -m pip install cibuildwheel==4.1.0

    - name: Build wheels
      run: python -m cibuildwheel --output-dir wheelhouse
      env:
        CIBW_SKIP: "*-win32 *-*linux_i686"
        LIBBLURAY_INCLUDE_DIR: ${{ github.workspace }}\libbluray\include\\libbluray
        LIBBLURAY_LIBRARY_DIR: ${{ github.workspace }}\libbluray\lib\x64
        CIBW_REPAIR_WHEEL_COMMAND_WINDOWS: delvewheel repair -w {dest_dir} -v {wheel} --add-path "${{ github.workspace }}\libbluray\bin\x64" --add-path "${{ github.workspace }}\libaacs\bin\x64" --include aacs.dll
      if: matrix.os == 'windows-latest'

    - name: Build wheels
      run: python -m cibuildwheel --output-dir wheelhouse
      env:
        CIBW_BEFORE_ALL_LINUX: dnf install -y libbluray-devel
        CIBW_MANYLINUX_X86_64_IMAGE: manylinux_2_34
        CIBW_SKIP: "*musllinux_*"
      if: matrix.os == 'ubuntu-latest'

    - uses: actions/upload-artifact@v6
      with:
        name: cibw-wheels-${{ matrix.os }}-${{ strategy.job-index }}
        path: ./wheelhouse/*.whl

  build_sdist:
    name: Build source distribution
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v6
      with:
        persist-credentials: false

    - name: Build sdist
      run: pipx run build --sdist

    - uses: actions/upload-artifact@v6
      with:
        name: cibw-sdist
        path: dist/*.tar.gz

  upload_pypi:
    needs: [ build_wheels, build_sdist ]
    runs-on: ubuntu-latest
    environment: pypi
    permissions:
      id-token: write
    # if: github.event_name == 'release' && github.event.action == 'published'
    # or, alternatively, upload to PyPI on every tag starting with 'v' (remove on: release above to use this)
    # if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags/v')
    steps:
    - uses: actions/download-artifact@v5
      with:
        # unpacks all CIBW artifacts into dist/
        pattern: cibw-*
        path: dist
        merge-multiple: true

    - uses: pypa/gh-action-pypi-publish@release/v1
      # To test uploads to TestPyPI, uncomment the following:
      with:
        repository-url: https://test.pypi.org/legacy/